import type {
  DataQualityIssue,
  DemoUser,
  GroupingRecommendation,
  InventoryImportBatch,
  InventoryItem,
  ReportSummary,
  StockMovement,
} from "./contracts";

export const demoUsers: DemoUser[] = [
  {
    id: "usr-admin",
    fullName: "Daniela Vargas",
    email: "daniela.vargas@agp.demo",
    role: "admin",
  },
  {
    id: "usr-commercial",
    fullName: "Luis Herrera",
    email: "luis.herrera@agp.demo",
    role: "commercial_analyst",
  },
  {
    id: "usr-warehouse",
    fullName: "Paola Garcia",
    email: "paola.garcia@agp.demo",
    role: "warehouse_operator",
  },
  {
    id: "usr-exec",
    fullName: "Sofia Martinez",
    email: "sofia.martinez@agp.demo",
    role: "executive_readonly",
  },
];

export const demoBatches: InventoryImportBatch[] = [
  {
    id: "imp-2026-04-12",
    fileName: "Mock_Data_sanitized.xlsx",
    sourceType: "xlsx",
    importedAt: "2026-04-12T10:15:00Z",
    totalRows: 3838,
    validRows: 3208,
    rowsNeedingReview: 630,
    status: "processed",
  },
  {
    id: "imp-2026-04-09",
    fileName: "inventory_snapshot_2026_04_09.csv",
    sourceType: "csv",
    importedAt: "2026-04-09T22:05:00Z",
    totalRows: 3812,
    validRows: 3189,
    rowsNeedingReview: 623,
    status: "processed",
  },
];

export const demoInventory: InventoryItem[] = [
  {
    id: "inv-001",
    orderId: "CM37V9621T571",
    serial: "634266691",
    vehicle: "Toyota Hilux",
    created: "2020-01-01",
    product: "Sample",
    invoice: "EXP109886",
    invoiceCost: 3356706,
    customer: "Acme Corporation",
    daysStored: 1847,
    setStatus: "Incomplete",
    operationalStatus: "In Stock",
    locationCode: "MX-A1-01",
    qrToken: "AGP-Q-INV-001",
    reviewReasons: [],
  },
  {
    id: "inv-002",
    orderId: "CM37V9621T900",
    serial: "50906963",
    vehicle: "Toyota Hilux",
    created: "2020-01-02",
    product: "Sample",
    invoice: "EXP105135",
    invoiceCost: 4795094,
    customer: null,
    daysStored: 1847,
    setStatus: "Additionals",
    operationalStatus: "In Stock",
    locationCode: "MX-A1-03",
    qrToken: "AGP-Q-INV-002",
    reviewReasons: [],
  },
  {
    id: "inv-003",
    orderId: "CM61R5806E810",
    serial: "673339352",
    vehicle: "Toyota Hilux",
    created: "2020-01-01",
    product: "C34",
    invoice: "EXP104673",
    invoiceCost: 4705140,
    customer: "Pinnacle Partners",
    daysStored: 1760,
    setStatus: "Incomplete",
    operationalStatus: "Review Needed",
    locationCode: "MX-B2-04",
    qrToken: "AGP-Q-INV-003",
    reviewReasons: ["Validar coincidencia de producto con comercial", "Pendiente de aprobacion humana"],
  },
  {
    id: "inv-004",
    orderId: "CM87S9952P528",
    serial: "509919028",
    vehicle: "Peugeot 208",
    created: "2020-01-01",
    product: "C34",
    invoice: "EXP101072",
    invoiceCost: 4199092,
    customer: null,
    daysStored: 1847,
    setStatus: "Complete",
    operationalStatus: "In Stock",
    locationCode: "MX-C4-01",
    qrToken: "AGP-Q-INV-004",
    reviewReasons: [],
  },
  {
    id: "inv-005",
    orderId: "CM12F2200L018",
    serial: "882774101",
    vehicle: "Ford Ranger",
    created: "2021-02-11",
    product: "C34",
    invoice: "EXP119301",
    invoiceCost: 2911045,
    customer: "Atlas Motors",
    daysStored: 1514,
    setStatus: "Incomplete",
    operationalStatus: "In Stock",
    locationCode: "MX-D1-02",
    qrToken: "AGP-Q-INV-005",
    reviewReasons: [],
  },
  {
    id: "inv-006",
    orderId: "CM12F2200L115",
    serial: "882774199",
    vehicle: "Ford Ranger",
    created: "2021-02-08",
    product: "C34",
    invoice: "EXP119314",
    invoiceCost: 2870120,
    customer: null,
    daysStored: 1517,
    setStatus: "Additionals",
    operationalStatus: "Reserved",
    locationCode: "MX-STAGE-01",
    qrToken: "AGP-Q-INV-006",
    reviewReasons: [],
  },
  {
    id: "inv-007",
    orderId: "CM98Z7700M102",
    serial: "771150101",
    vehicle: "Chevrolet Colorado",
    created: "2021-06-19",
    product: "C12",
    invoice: "EXP121880",
    invoiceCost: 3159987,
    customer: "Solaris Fleet",
    daysStored: 1388,
    setStatus: "Incomplete",
    operationalStatus: "Completed",
    locationCode: "MX-F2-01",
    qrToken: "AGP-Q-INV-007",
    reviewReasons: [],
  },
  {
    id: "inv-008",
    orderId: "CM98Z7700M330",
    serial: "771150188",
    vehicle: "Chevrolet Colorado",
    created: "2021-06-15",
    product: "C12",
    invoice: "EXP121881",
    invoiceCost: 1305500,
    customer: "Solaris Fleet",
    daysStored: 1392,
    setStatus: "Additionals",
    operationalStatus: "Grouped",
    locationCode: "MX-F2-01",
    qrToken: "AGP-Q-INV-008",
    reviewReasons: [],
  },
  {
    id: "inv-009",
    orderId: "CM45Q1144A778",
    serial: "117885442",
    vehicle: "Nissan NP300",
    created: "2022-04-03",
    product: "C12",
    invoice: "EXP125510",
    invoiceCost: 1984200,
    customer: null,
    daysStored: 1099,
    setStatus: "Incomplete",
    operationalStatus: "Blocked",
    locationCode: "MX-G3-06",
    qrToken: "AGP-Q-INV-009",
    reviewReasons: ["Producto con observacion de calidad"],
  },
  {
    id: "inv-010",
    orderId: "CM37V9621T572",
    serial: "634266692",
    vehicle: "Toyota Hilux",
    created: "2022-11-28",
    product: "Sample",
    invoice: "EXP129980",
    invoiceCost: 3321000,
    customer: "Acme Corporation",
    daysStored: 865,
    setStatus: "Complete",
    operationalStatus: "Ready for Dispatch",
    locationCode: "MX-DOCK-02",
    qrToken: "AGP-Q-INV-010",
    reviewReasons: [],
  },
  {
    id: "inv-011",
    orderId: "CM37V9621T901",
    serial: "634266693",
    vehicle: "Toyota Hilux",
    created: "2022-11-18",
    product: "Sample",
    invoice: "EXP129981",
    invoiceCost: 1221000,
    customer: null,
    daysStored: 875,
    setStatus: "Additionals",
    operationalStatus: "In Stock",
    locationCode: "MX-A3-04",
    qrToken: "AGP-Q-INV-011",
    reviewReasons: [],
  },
  {
    id: "inv-012",
    orderId: "CM11B5010C902",
    serial: "991270188",
    vehicle: null,
    created: "2023-02-02",
    product: "C34",
    invoice: "EXP131004",
    invoiceCost: 2110000,
    customer: null,
    daysStored: 798,
    setStatus: "Incomplete",
    operationalStatus: "Review Needed",
    locationCode: "MX-REVIEW-01",
    qrToken: "AGP-Q-INV-012",
    reviewReasons: ["Vehicle vacio excluye agrupacion automatica"],
  },
];

export const demoIssues: DataQualityIssue[] = [
  {
    itemId: "inv-002",
    severity: "info",
    field: "Customer",
    message: "Customer vacio tratado como stock libre.",
    issueCode: "missing_customer",
  },
  {
    itemId: "inv-003",
    severity: "warning",
    field: "Product",
    message: "Registro marcado para revision antes de agrupar por posible inconsistencia comercial.",
    issueCode: "suspicious_combination",
  },
  {
    itemId: "inv-009",
    severity: "error",
    field: "Product",
    message: "Producto bloqueado por observacion de calidad.",
    issueCode: "suspicious_combination",
  },
  {
    itemId: "inv-012",
    severity: "warning",
    field: "Vehicle",
    message: "Vehicle vacio deja el item fuera de agrupacion automatica.",
    issueCode: "missing_vehicle",
  },
  {
    itemId: "inv-012",
    severity: "info",
    field: "Customer",
    message: "Customer vacio tratado como stock libre solo despues de revision.",
    issueCode: "missing_customer",
  },
];

export const demoRecommendations: GroupingRecommendation[] = [
  {
    id: "grp-001",
    receiverId: "inv-001",
    receiverOrderId: "CM37V9621T571",
    receiverCustomer: "Acme Corporation",
    receiverVehicle: "Toyota Hilux",
    receiverProduct: "Sample",
    receiverDaysStored: 1847,
    decisionStatus: "pending",
    primaryCandidate: {
      donorId: "inv-011",
      donorOrderId: "CM37V9621T901",
      donorCustomer: null,
      donorVehicle: "Toyota Hilux",
      donorProduct: "Sample",
      donorSetStatus: "Additionals",
      sourceType: "free_stock",
      rank: 1,
      daysStoredAtDecision: 875,
      explanation:
        "Se selecciona porque coincide en Vehicle y Product, proviene de stock libre y es el item mas antiguo disponible dentro del universo compatible.",
    },
    candidates: [
      {
        donorId: "inv-011",
        donorOrderId: "CM37V9621T901",
        donorCustomer: null,
        donorVehicle: "Toyota Hilux",
        donorProduct: "Sample",
        donorSetStatus: "Additionals",
        sourceType: "free_stock",
        rank: 1,
        daysStoredAtDecision: 875,
        explanation:
          "Se selecciona porque coincide en Vehicle y Product, proviene de stock libre y es el item mas antiguo disponible dentro del universo compatible.",
      },
      {
        donorId: "inv-002",
        donorOrderId: "CM37V9621T900",
        donorCustomer: null,
        donorVehicle: "Toyota Hilux",
        donorProduct: "Sample",
        donorSetStatus: "Additionals",
        sourceType: "free_stock",
        rank: 2,
        daysStoredAtDecision: 1847,
        explanation:
          "Alternativa valida con mayor antiguedad, relegada por disponibilidad operativa en la zona actual.",
      },
    ],
    summary:
      "Completa CM37V9621T571 con stock libre compatible priorizando la mayor antiguedad.",
  },
  {
    id: "grp-002",
    receiverId: "inv-005",
    receiverOrderId: "CM12F2200L018",
    receiverCustomer: "Atlas Motors",
    receiverVehicle: "Ford Ranger",
    receiverProduct: "C34",
    receiverDaysStored: 1514,
    decisionStatus: "pending",
    primaryCandidate: {
      donorId: "inv-006",
      donorOrderId: "CM12F2200L115",
      donorCustomer: null,
      donorVehicle: "Ford Ranger",
      donorProduct: "C34",
      donorSetStatus: "Additionals",
      sourceType: "additional",
      rank: 1,
      daysStoredAtDecision: 1517,
      explanation:
        "Adicional compatible en stock libre con prioridad FEFO y mismo Vehicle/Product.",
    },
    candidates: [
      {
        donorId: "inv-006",
        donorOrderId: "CM12F2200L115",
        donorCustomer: null,
        donorVehicle: "Ford Ranger",
        donorProduct: "C34",
        donorSetStatus: "Additionals",
        sourceType: "additional",
        rank: 1,
        daysStoredAtDecision: 1517,
        explanation:
          "Adicional compatible en stock libre con prioridad FEFO y mismo Vehicle/Product.",
      },
    ],
    summary:
      "Agrupamiento directo para Atlas Motors usando adicional libre compatible.",
  },
  {
    id: "grp-003",
    receiverId: "inv-007",
    receiverOrderId: "CM98Z7700M102",
    receiverCustomer: "Solaris Fleet",
    receiverVehicle: "Chevrolet Colorado",
    receiverProduct: "C12",
    receiverDaysStored: 1388,
    decisionStatus: "approved",
    primaryCandidate: {
      donorId: "inv-008",
      donorOrderId: "CM98Z7700M330",
      donorCustomer: "Solaris Fleet",
      donorVehicle: "Chevrolet Colorado",
      donorProduct: "C12",
      donorSetStatus: "Additionals",
      sourceType: "additional",
      rank: 1,
      daysStoredAtDecision: 1392,
      explanation:
        "Mismo cliente, mismo vehiculo y adicional mas antiguo disponible.",
    },
    candidates: [
      {
        donorId: "inv-008",
        donorOrderId: "CM98Z7700M330",
        donorCustomer: "Solaris Fleet",
        donorVehicle: "Chevrolet Colorado",
        donorProduct: "C12",
        donorSetStatus: "Additionals",
        sourceType: "additional",
        rank: 1,
        daysStoredAtDecision: 1392,
        explanation:
          "Mismo cliente, mismo vehiculo y adicional mas antiguo disponible.",
      },
    ],
    summary:
      "Agrupamiento aprobado y trazado en bodega para Solaris Fleet.",
  },
  {
    id: "grp-004",
    receiverId: "inv-003",
    receiverOrderId: "CM61R5806E810",
    receiverCustomer: "Pinnacle Partners",
    receiverVehicle: "Toyota Hilux",
    receiverProduct: "C34",
    receiverDaysStored: 1760,
    decisionStatus: "rejected",
    primaryCandidate: {
      donorId: "inv-002",
      donorOrderId: "CM37V9621T900",
      donorCustomer: null,
      donorVehicle: "Toyota Hilux",
      donorProduct: "Sample",
      donorSetStatus: "Additionals",
      sourceType: "free_stock",
      rank: 1,
      daysStoredAtDecision: 1847,
      explanation:
        "Se propuso por compatibilidad parcial de vehiculo, pero requiere validacion comercial del Product.",
    },
    candidates: [
      {
        donorId: "inv-002",
        donorOrderId: "CM37V9621T900",
        donorCustomer: null,
        donorVehicle: "Toyota Hilux",
        donorProduct: "Sample",
        donorSetStatus: "Additionals",
        sourceType: "free_stock",
        rank: 1,
        daysStoredAtDecision: 1847,
        explanation:
          "Se propuso por compatibilidad parcial de vehiculo, pero requiere validacion comercial del Product.",
      },
    ],
    summary:
      "Rechazado por incompatibilidad funcional del producto y necesidad de revision humana.",
  },
];

export const demoMovements: StockMovement[] = [
  {
    id: "mov-001",
    itemId: "inv-008",
    action: "group",
    fromStatus: "In Stock",
    toStatus: "Grouped",
    fromLocation: "MX-F2-01",
    toLocation: "MX-STAGE-02",
    actorName: "Paola Garcia",
    occurredAt: "2026-04-12T13:24:00Z",
    notes: "Consumido como donante para la recomendacion grp-003.",
  },
  {
    id: "mov-002",
    itemId: "inv-007",
    action: "complete",
    fromStatus: "In Stock",
    toStatus: "Completed",
    fromLocation: "MX-F2-01",
    toLocation: "MX-QA-01",
    actorName: "Luis Herrera",
    occurredAt: "2026-04-12T13:27:00Z",
    notes: "Receptor completado despues de aprobacion comercial.",
  },
  {
    id: "mov-003",
    itemId: "inv-006",
    action: "reserve",
    fromStatus: "In Stock",
    toStatus: "Reserved",
    fromLocation: "MX-D1-03",
    toLocation: "MX-STAGE-01",
    actorName: "Paola Garcia",
    occurredAt: "2026-04-12T14:05:00Z",
    notes: "Reservado para la recomendacion grp-002.",
  },
  {
    id: "mov-004",
    itemId: "inv-010",
    action: "dispatch",
    fromStatus: "Ready for Dispatch",
    toStatus: "Dispatched",
    fromLocation: "MX-DOCK-02",
    toLocation: "Outbound",
    actorName: "Sofia Martinez",
    occurredAt: "2026-04-12T15:40:00Z",
    notes: "Despacho autorizado para cliente Acme Corporation.",
  },
];

export const demoSummary: ReportSummary = {
  totalInventory: 3838,
  completeSets: 1323,
  incompleteSets: 2121,
  additionals: 394,
  freeStock: 993,
  reviewNeeded: 630,
  recommendationsPending: 1483,
  recommendationsApproved: 0,
  oldestDaysStored: 1847,
};
