"""initial schema

Revision ID: 0d1bd4e3ccf9
Revises: 
Create Date: 2026-04-12 12:15:46.308152
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0d1bd4e3ccf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('inventory_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('rows_needing_review', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_import_batches_batch_uuid'), 'inventory_import_batches', ['batch_uuid'], unique=True)
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_types_name'), 'product_types', ['name'], unique=True)
    op.create_table('status_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Enum('IN_STOCK', 'RESERVED', 'GROUPED', 'COMPLETED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'BLOCKED', 'REVIEW_NEEDED', name='operationalstatus'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_catalog_status_code'), 'status_catalog', ['status_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COMMERCIAL_ANALYST', 'WAREHOUSE_OPERATOR', 'EXECUTIVE_READONLY', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_uuid'), 'users', ['user_uuid'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_name'), 'vehicles', ['name'], unique=True)
    op.create_table('warehouse_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('aisle', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_locations_code'), 'warehouse_locations', ['code'], unique=True)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=False),
    sa.Column('vehicle_name', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('invoice', sa.String(length=100), nullable=False),
    sa.Column('invoice_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('days_stored', sa.Integer(), nullable=False),
    sa.Column('set_status', sa.Enum('COMPLETE', 'INCOMPLETE', 'ADDITIONALS', name='sourcesetstatus'), nullable=False),
    sa.Column('operational_status', sa.Enum('IN_STOCK', 'RESERVED', 'GROUPED', 'COMPLETED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'BLOCKED', 'REVIEW_NEEDED', name='operationalstatus'), nullable=False),
    sa.Column('is_free_stock', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['inventory_import_batches.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_inventory_items_source_id')
    )
    op.create_index(op.f('ix_inventory_items_customer_name'), 'inventory_items', ['customer_name'], unique=False)
    op.create_index(op.f('ix_inventory_items_days_stored'), 'inventory_items', ['days_stored'], unique=False)
    op.create_index(op.f('ix_inventory_items_is_free_stock'), 'inventory_items', ['is_free_stock'], unique=False)
    op.create_index('ix_inventory_items_lookup', 'inventory_items', ['order_id', 'vehicle_name', 'product_name'], unique=False)
    op.create_index(op.f('ix_inventory_items_needs_review'), 'inventory_items', ['needs_review'], unique=False)
    op.create_index(op.f('ix_inventory_items_order_id'), 'inventory_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_product_name'), 'inventory_items', ['product_name'], unique=False)
    op.create_index(op.f('ix_inventory_items_serial'), 'inventory_items', ['serial'], unique=False)
    op.create_index(op.f('ix_inventory_items_set_status'), 'inventory_items', ['set_status'], unique=False)
    op.create_index('ix_inventory_items_status', 'inventory_items', ['set_status', 'operational_status'], unique=False)
    op.create_table('grouping_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_uuid', sa.String(length=36), nullable=False),
    sa.Column('receiver_item_id', sa.Integer(), nullable=False),
    sa.Column('decision_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='groupingdecisionstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('selected_donor_item_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receiver_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['selected_donor_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grouping_recommendations_analysis_run_id'), 'grouping_recommendations', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_grouping_recommendations_receiver_item_id'), 'grouping_recommendations', ['receiver_item_id'], unique=False)
    op.create_index(op.f('ix_grouping_recommendations_recommendation_uuid'), 'grouping_recommendations', ['recommendation_uuid'], unique=True)
    op.create_index('ix_grouping_recommendations_status', 'grouping_recommendations', ['decision_status', 'receiver_item_id'], unique=False)
    op.create_table('qr_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_token', sa.String(length=120), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id')
    )
    op.create_index(op.f('ix_qr_tags_qr_token'), 'qr_tags', ['qr_token'], unique=True)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_uuid', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('from_status', sa.Enum('IN_STOCK', 'RESERVED', 'GROUPED', 'COMPLETED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'BLOCKED', 'REVIEW_NEEDED', name='operationalstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('IN_STOCK', 'RESERVED', 'GROUPED', 'COMPLETED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'BLOCKED', 'REVIEW_NEEDED', name='operationalstatus'), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['warehouse_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_action'), 'stock_movements', ['action'], unique=False)
    op.create_index(op.f('ix_stock_movements_inventory_item_id'), 'stock_movements', ['inventory_item_id'], unique=False)
    op.create_index('ix_stock_movements_item', 'stock_movements', ['inventory_item_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_uuid'), 'stock_movements', ['movement_uuid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_uuid', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('IMPORT', 'GROUPING_ANALYSIS', 'GROUPING_APPROVED', 'GROUPING_REJECTED', 'SCAN', 'MOVEMENT', name='auditeventtype'), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['grouping_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_event', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_uuid'), 'audit_logs', ['event_uuid'], unique=True)
    op.create_table('grouping_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('donor_item_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ADDITIONAL', 'INCOMPLETE', 'FREE_STOCK', name='groupingsourcetype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('days_stored_at_decision', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donor_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['grouping_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grouping_matches_donor_item_id'), 'grouping_matches', ['donor_item_id'], unique=False)
    op.create_index('ix_grouping_matches_rank', 'grouping_matches', ['recommendation_id', 'rank'], unique=False)
    op.create_index(op.f('ix_grouping_matches_recommendation_id'), 'grouping_matches', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grouping_matches_recommendation_id'), table_name='grouping_matches')
    op.drop_index('ix_grouping_matches_rank', table_name='grouping_matches')
    op.drop_index(op.f('ix_grouping_matches_donor_item_id'), table_name='grouping_matches')
    op.drop_table('grouping_matches')
    op.drop_index(op.f('ix_audit_logs_event_uuid'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_event', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_stock_movements_movement_uuid'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_item', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_inventory_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_action'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_qr_tags_qr_token'), table_name='qr_tags')
    op.drop_table('qr_tags')
    op.drop_index('ix_grouping_recommendations_status', table_name='grouping_recommendations')
    op.drop_index(op.f('ix_grouping_recommendations_recommendation_uuid'), table_name='grouping_recommendations')
    op.drop_index(op.f('ix_grouping_recommendations_receiver_item_id'), table_name='grouping_recommendations')
    op.drop_index(op.f('ix_grouping_recommendations_analysis_run_id'), table_name='grouping_recommendations')
    op.drop_table('grouping_recommendations')
    op.drop_index('ix_inventory_items_status', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_set_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_serial'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_product_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_order_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_needs_review'), table_name='inventory_items')
    op.drop_index('ix_inventory_items_lookup', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_is_free_stock'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_days_stored'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_customer_name'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_warehouse_locations_code'), table_name='warehouse_locations')
    op.drop_table('warehouse_locations')
    op.drop_index(op.f('ix_vehicles_name'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_user_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_status_catalog_status_code'), table_name='status_catalog')
    op.drop_table('status_catalog')
    op.drop_index(op.f('ix_product_types_name'), table_name='product_types')
    op.drop_table('product_types')
    op.drop_index(op.f('ix_inventory_import_batches_batch_uuid'), table_name='inventory_import_batches')
    op.drop_table('inventory_import_batches')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
